//! `magic` — the attention queue: what claims a HUMAN right now, and what the
//! base has to be able to do so the scene can act on it.
//!
//! IT IS TWO CONTRACTS IN ONE FILE ON PURPOSE. The DATA (`AttentionClaim` and
//! everything under it) and the PORTS (`MagicPorts`) cannot be split: every
//! port signature is written in terms of the data, and a file holding only the
//! verbs would import the nouns from the scene — the base depending on the
//! screen it is supposed to feed. One file, read top to bottom: what a claim
//! is, then what somebody must do to deliver and answer one.
//!
//! ATTENTION IS NOT PRIORITY. A P0 an agent finishes alone makes no claim on a
//! person; a five-second "A or B?" blocking three agents makes a loud one.
//! Everything here describes the claim on a HUMAN, never the importance of the
//! work.
//!
//! THE SCENE NEVER FETCHES. `@my/scene-magic` renders these types and
//! calls these ports; it holds no URL, no route name and no socket path. That
//! is what lets the same screen run inside `apps/my` over HTTP, inside a story
//! with a hand-written queue, and inside a test with none of either. The route
//! `apps/web_app/app/api/attention/route.ts` is ONE implementation of `readQueue`,
//! not the definition of it — see `packages/scene-magic/CONTEXT.md`.
//!
//! OPEN ENUMS. `ClaimKind` and `AttentionLevel` are written by whatever ranked
//! the claim. A build with no surface for a kind prints the kind and the words
//! that came with it; it never drops the claim.
//!
//! implemented: packages/scene-magic/src/lib/attention.ts (rank, the caps) ·
//!              packages/scene-magic/src/AttentionPolicy.ts (levelOf)
//! not yet:     apps/my — no base exists today, so no port has an implementation
//!              in this repo. `_today/apps/agent_conversation/app/api/` holds the
//!              routes these signatures were measured from, on 21/08.

// ─────────────────────────────────────────────────────────────────────────────
// The claim
// ─────────────────────────────────────────────────────────────────────────────

/** How far a claim may go to reach you. */
export type AttentionLevel =
  /** May replace what is on the stage right now. */
  | "interrupt"
  /** Enters the queue; never steals the current decision. */
  | "next"
  /** Visible elsewhere; never surfaces here on its own. */
  | "passive";

/** What kind of thing is claiming the screen — decides which lenses fit. */
export type ClaimKind = "review" | "question" | "blocked" | "command" | "issue";

/** Where the claim came from, in the words the rest of the house already uses. */
export type ClaimSource = {
  /** The channel that owns the work, and that will receive any answer. */
  channel: string;
  /** Issue or PR number when there is one. */
  number?: number;
  /** The agent that is waiting, when a specific one is. */
  agent?: string;
  /** GitHub URL when the claim is about an issue. */
  url?: string;
};

/**
 * One reason this deserves a person, in words.
 *
 * The score is an implementation detail; these are the interface. A screen that
 * prints 87 explains nothing, and a screen that prints "blocked · 18m · asked
 * you" explains the whole ranking.
 */
export type ClaimReason = {
  /** Short label: `blocked`, `asked you`, `oldest`, `three agents waiting`. */
  label: string;
  /** What this reason contributed to the rank. Never rendered as a number. */
  weight: number;
};

/**
 * What the agent already knows, written by the agent, at the moment it asked.
 *
 * NOT generated by the reader. The agent that did the work has just read every
 * line of it; asking a model to re-derive that from the same text costs tokens,
 * adds a wait, and produces a SECOND version of somebody's words that can drift
 * from the first. The one who knows writes it down.
 *
 * The format is the contract, and it is small on purpose: fourteen words is
 * what a person reads before deciding whether to read the rest.
 */
export type ClaimSummary = {
  /** One paragraph, at most `SUMMARY_WORDS` words. Longer is refused, not cut. */
  text: string;
  /** At most `SUMMARY_BULLETS`, one line each. */
  bullets?: string[];
  /** One mermaid graph, for a real flow or dependency. */
  mermaid?: string;
  /** One markdown table, when the content already is one. */
  table?: string;
  /** One absolute path the base can serve through `MagicPorts.imageUrl`. */
  image?: string;
};

/** A line the claim quotes for context: who said it, what, and when. */
export type ClaimContextLine = { from: string; text: string; at: number | null };

export type AttentionClaim = {
  /** Stable across recomputes: `<channel>#<number>@<kind>` or `<channel>:<agent>`. */
  id: string;
  kind: ClaimKind;
  level: AttentionLevel;
  source: ClaimSource;
  /** One sentence: what the human is being asked. Quoted, never invented. */
  headline: string;
  /** ISO8601 — when the need started, not when it was noticed. */
  since: string;
  reasons: ClaimReason[];
  /** Written by the agent that asked. Absent is a real state: it means nobody
   *  summarised this, and the screen says so rather than inventing one. */
  summary?: ClaimSummary;
  /** The lines immediately before the ask, quoted. A question torn out of its
   *  conversation reads as a riddle. */
  context?: ClaimContextLine[];
  /** Sum of the reasons' weights. Ordering only; never printed raw. */
  score: number;
};

/** Everything a lens can be asked to render. */
export type LensId = "graph" | "timeline" | "table" | "diff" | "surface" | "raw";

/** What the queue decided, plus how it decided — one read of `readQueue`. */
export type AttentionState = {
  claims: AttentionClaim[];
  /** ISO8601 of the computation, so a quiet screen can prove it is fresh. */
  at: string;
  /** Sources that could not be read: quiet must never be built on silence. */
  unread: string[];
};

// ─────────────────────────────────────────────────────────────────────────────
// The review, which is a line in a channel and not a row in a database
// ─────────────────────────────────────────────────────────────────────────────

export type Verdict = "validated" | "needs_work";

export type ReviewLine = {
  type: "review";
  /** Stable id: channel, issue number, and the second it was written. */
  id: string;
  from: string;
  role: string;
  channel: string;
  /** The card this judges. */
  issue: number;
  verdict: Verdict;
  ts: string;
  text: string;
};

/** One thing said after a verdict — an agent's answer, or more human feedback. */
export type ReviewMessage = {
  id: string;
  from: string;
  ts: string;
  text: string;
  /** True when the human wrote it, so the thread can show both sides. */
  mine: boolean;
};

export type ReviewThread = {
  review: ReviewLine | null;
  messages: ReviewMessage[];
  /** URLs the channel has mentioned for this card, newest first. */
  previews: string[];
};

/** A file that rides with a write, marked `[File #n]` in the prose. */
export type Attachment = { n: number; path: string; mime: string; bytes: number };

// ─────────────────────────────────────────────────────────────────────────────
// The issue, read rather than framed
// ─────────────────────────────────────────────────────────────────────────────

export type IssueComment = { author: string; body: string; createdAt: string };

export type IssueRef = {
  number: number;
  /** open | closed | merged — merged is a closed PR, and they read differently. */
  state: string;
  title: string;
  url: string;
};

export type IssueDetail = {
  repository: string;
  number: number;
  title: string;
  state: string;
  author: string;
  createdAt: string;
  url: string;
  body: string;
  comments: IssueComment[];
  /** Comments the tail does not carry, so the screen can say how many. */
  moreComments: number;
  /** Every issue or PR the body names, with the state it is in right now. */
  references: IssueRef[];
  /** References beyond the cap, so the chip row never lies by omission. */
  moreReferences: number;
};

/** What a preview URL actually answers, measured by whoever can measure it. */
export type Probe = {
  url: string;
  status: number;
  contentType: string;
  bytes: number;
  /** A page is what an iframe can render into something worth judging. */
  isPage: boolean;
  error?: string;
};

// ─────────────────────────────────────────────────────────────────────────────
// The ports — what the base must be able to do
// ─────────────────────────────────────────────────────────────────────────────

/** What the caller wants written. `text` is the exact line the channel gets. */
export type ChannelCommand = {
  channel: string;
  text: string;
  /** The agent it is addressed to; the envelope rides in the line. */
  to?: string;
  issue?: number;
  files?: { n: number; path: string }[];
};

/** What the channel gave back — MEASURED, not believed. A write is not sent
 *  until the implementation has read its own line back and can name the seq. */
export type ChannelReceipt = {
  id: string;
  channel: string;
  to: string | null;
  seq: number;
  via: "bus" | "file";
};

/** A verdict, on its way into the channel that owns the card. */
export type VerdictWrite = {
  channel: string;
  issue: number;
  verdict: Verdict;
  text: string;
  files?: { n: number; path: string }[];
};

/** More feedback under a verdict already written. `re` threads it by id. */
export type ReviewReplyWrite = {
  channel: string;
  issue: number;
  /** The `ReviewLine.id` this answers. */
  re: string;
  text: string;
  files?: { n: number; path: string }[];
};

/**
 * The answer to any write.
 *
 * `ok: false` carries a sentence a person can act on, and the failure travels
 * in the BODY rather than in a status code — measured on `/api/review`, which
 * answers 200 with `{ok:false}` when the channel refused the line. A caller
 * that only checks the status calls a refusal a success.
 */
export type Written = { ok: true } | { ok: false; error: string };

/** The answer to an attach: where the file landed, so the marker can point. */
export type Attached =
  | { ok: true; path: string; bytes: number }
  | { ok: false; error: string };

/**
 * Everything `@my/scene-magic` needs from the world, and nothing more.
 *
 * The base implements this and hands it down once; every component in the
 * scene calls it through context. Nine verbs is the whole surface — if a
 * screen in this scene ever needs a tenth, it is a new capability and it gets
 * argued for here, in the open, rather than appearing as a `fetch` inside a
 * component where nobody reviews it.
 *
 * Every method may reject. The scene prints what a rejection says: a queue that
 * cannot be read is a different screen from a queue that came back empty, and
 * collapsing them is the CONFIDENT ZERO this whole system exists to prevent.
 */
export type MagicPorts = {
  /** Who deserves a human right now. Called on an interval by the scene. */
  readQueue(signal?: AbortSignal): Promise<AttentionState>;

  /** The verdict on a card and everything said after it. */
  readReview(channel: string, issue: number): Promise<ReviewThread>;

  /** A human's verdict, written into the channel that owns the work. */
  writeVerdict(write: VerdictWrite): Promise<Written>;

  /** More feedback under a verdict, threaded by `re`. Appends, never edits. */
  replyToReview(write: ReviewReplyWrite): Promise<Written>;

  /** One line into a channel, with the seq the file gave it back. */
  sendCommand(command: ChannelCommand): Promise<ChannelReceipt | { error: string }>;

  /** A pasted blob, saved where an agent can open it by path. */
  attach(a: { channel: string; issue: number; mime: string; dataBase64: string }): Promise<Attached>;

  /** One issue, read — GitHub sends `X-Frame-Options: DENY`, so it cannot be framed. */
  readIssue(url: string): Promise<IssueDetail>;

  /** What a preview URL answers. An iframe reports success for a 404, an empty
   *  body and a JSON payload alike — all three paint white. */
  probePreview(url: string): Promise<Probe>;

  /** A servable URL for an absolute path on disk. Synchronous: it goes into a
   *  `src` attribute, and a promise there is a blank image for one frame. */
  imageUrl(path: string): string;
};
