//! Turns each company workflow into a project-scope skill under
//! `.claude/skills/my_<name>/SKILL.md`.
//!
//! The generated file is DERIVED and carries a header saying so. Editing it by
//! hand creates the second truth the generator exists to remove — the fix goes in
//! the workflow's `CONTEXT.md`, and the next run carries it over.
//!
//! `my_` is the prefix because a bare `research` or `whatsapp` would sit next to
//! 111 user skills and say nothing about where it came from.
//!
//! depends_on: ./workflows.ts

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { COMPANY, type Workflow, home, workflows } from "./workflows.ts";

export const SKILLS = (): string => join(home(), ".claude", "skills");

export const PREFIX = "my_";

/** The line that marks a file as generated. A file without it is somebody's
 *  hand-written skill, and the generator must never overwrite or delete it. */
export const MARK = "<!-- GENERATED by `my company skills` — edit the workflow, not this file. -->";

/** The folder name is the address; the skill name is what a person types.
 *
 *  `NN_` is ORDER, not identity — `01_support` and `03_validate` would carry a
 *  number that means nothing outside its parent. `_` in front is namespace, the
 *  same convention `_parked` uses, so `_contract` is not a workflow anybody
 *  invokes and it produced `my__contract` before this existed. */
export function skillName(folder: string): string | undefined {
	if (folder.startsWith("_")) return undefined;
	const bare = folder.replace(/^\d+_/, "");
	return bare ? `${PREFIX}${bare}` : undefined;
}

export type Planned = {
	skill: string;
	dir: string;
	workflow: Workflow;
	body: string;
	/** What is missing for this skill to be good, if anything. */
	gap?: string;
};

export function describe(w: Workflow): { description: string; gap?: string } {
	if (w.declared?.description) {
		const triggers = w.declared.triggers?.length ? ` Dispara em: ${w.declared.triggers.join(", ")}.` : "";
		return { description: w.declared.description + triggers, gap: w.declared.triggers?.length ? undefined : "sem `triggers:`" };
	}
	if (w.thesis) {
		// No invented trigger phrases: what a person would type to reach this is a
		// judgement the file has to state, and guessing it is how a skill fires on
		// the wrong request.
		return { description: `Workflow \`${w.rel}\` da casa: ${w.thesis}`, gap: "sem `skill:` no frontmatter — descrição derivada da tese, e sem frases de disparo" };
	}
	return { description: `Workflow \`${w.rel}\` da casa.`, gap: "o CONTEXT.md não tem tese nem `skill:` — nada legível pra derivar" };
}

export function plan(all = workflows()): Planned[] {
	const rows: (Planned | undefined)[] = all
		.filter((w) => !w.declared?.skip)
		.map((w) => {
			const skill = skillName(w.name);
			if (!skill) return undefined;
			const { description, gap } = describe(w);
			const body = [
				"---",
				"type: skill",
				`name: ${skill}`,
				`description: ${JSON.stringify(description)}`,
				"---",
				"",
				MARK,
				"",
				`# ${skill} — ${w.title}`,
				"",
				`Value stream: \`${w.stream}\``,
				"",
				"O contrato inteiro, e a única fonte:",
				"",
				`    my resources read 03_resources/00_company/${w.rel}/CONTEXT.md`,
				"",
				`Leia-o antes de agir. Esta página é ponteiro; ela não repete o workflow, e`,
				"quando os dois divergirem o `CONTEXT.md` é quem está certo.",
				"",
			].join("\n");
			return { skill, dir: join(SKILLS(), skill), workflow: w, body, gap } as Planned;
		});
	return rows.filter((p): p is Planned => p !== undefined);
}

/** Every generated skill on disk right now, by the mark. */
export function existing(): string[] {
	const root = SKILLS();
	if (!existsSync(root)) return [];
	return readdirSync(root)
		.filter((d) => d.startsWith(PREFIX))
		.filter((d) => {
			try {
				return readFileSync(join(root, d, "SKILL.md"), "utf8").includes(MARK);
			} catch {
				return false;
			}
		})
		.sort();
}

export type Applied = { written: string[]; unchanged: string[]; removed: string[]; gaps: { skill: string; gap: string }[] };

export function apply(dryRun = false): Applied {
	const planned = plan();
	const out: Applied = { written: [], unchanged: [], removed: [], gaps: [] };

	for (const p of planned) {
		if (p.gap) out.gaps.push({ skill: p.skill, gap: p.gap });
		const file = join(p.dir, "SKILL.md");
		let current = "";
		try {
			current = readFileSync(file, "utf8");
		} catch {
			current = "";
		}
		// A hand-written skill that happens to share the name is never overwritten:
		// the mark is the only licence this generator has to write.
		if (current && !current.includes(MARK)) {
			out.gaps.push({ skill: p.skill, gap: "existe escrito à mão e NÃO foi tocado — renomeie um dos dois" });
			continue;
		}
		if (current === p.body) {
			out.unchanged.push(p.skill);
			continue;
		}
		if (!dryRun) {
			mkdirSync(p.dir, { recursive: true });
			writeFileSync(file, p.body);
		}
		out.written.push(p.skill);
	}

	// A workflow that was deleted or renamed leaves its skill behind, and a skill
	// pointing at a workflow that no longer exists is worse than none.
	const wanted = new Set(planned.map((p) => p.skill));
	for (const s of existing()) {
		if (wanted.has(s)) continue;
		if (!dryRun) rmSync(join(SKILLS(), s), { recursive: true, force: true });
		out.removed.push(s);
	}

	return out;
}

/** What is out of date without writing anything: the check a gate can run. */
export function check(): { skill: string; says: string }[] {
	const found: { skill: string; says: string }[] = [];
	const dry = apply(true);
	for (const s of dry.written) found.push({ skill: s, says: "faltando ou desatualizado — rode `my company skills`" });
	for (const s of dry.removed) found.push({ skill: s, says: "o workflow sumiu, e a skill ficou" });
	for (const g of dry.gaps) found.push({ skill: g.skill, says: g.gap });
	if (!existsSync(COMPANY())) found.push({ skill: "—", says: `${COMPANY()} não existe` });
	return found;
}
